{
 "title": "KubeDNS",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Probe Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(kubedns_probe_dnsmasq_latency_ms_sum[1m])) / sum by (instance) (rate(kubedns_probe_dnsmasq_latency_ms_count[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{job=\"kube-dns\"})"
    }
   ]
  },
  {
   "title": "Dnsmasq Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kubedns_dnsmasq_misses[2m]))",
     "legendFormat": "Misses"
    },
    {
     "expr": "sum (rate(kubedns_dnsmasq_errors[1m]))",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum (rate(kubedns_dnsmasq_hits[1m]))",
     "legendFormat": "Hits"
    },
    {
     "expr": "sum (rate(kubedns_dnsmasq_insertions[1m]))",
     "legendFormat": "Insertions"
    },
    {
     "expr": "sum (rate(kubedns_dnsmasq_misses[1m]))",
     "legendFormat": "Misses"
    }
   ]
  }
 ]
}