dependencies:
  - name: grafana
    version: ^1.14.6
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: grafana.enabled
  - name: prometheus
    version: ^7.0.3
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: prometheus.enabled
  - name: elasticsearch
    version: ^1.1.3
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    condition: elasticsearch.enabled
  - name: kibana
    version: ^0.10.0
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: kibana.enabled
  - name: fluentd-elasticsearch
    version: ^0.7.0
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    condition: fluentd-elasticsearch.enabled
  - name: elasticsearch-curator
    version: ^0.3.0
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    condition: elasticsearch-curator.enabled
  - name: nginx-ingress
    version: ^0.23.0
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: nginx-ingress.enabled
  - name: cert-manager
    version: ^0.4.0
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: cert-manager.enabled
  - name: external-dns
    version: ^0.7.1
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: external-dns.enabled
  - name: metallb
    version: ^0.7.0
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: metallb.enabled