dependencies:
  - name: grafana
    version: ^1.14.8
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: cluster-svc.grafana.enabled
    tags:
      - monitoring
  - name: prometheus
    version: ^7.1.3
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: cluster-svc.prometheus.enabled
    tags:
      - monitoring
  - name: elasticsearch
    version: ^1.8.1
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    condition: cluster-svc.elasticsearch.enabled
    tags:
      - ELK
  - name: kibana
    version: ^0.14.6
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: cluster-svc.kibana.enabled
    tags:
      - ELK
  - name: fluentd-elasticsearch
    version: ^0.7.2
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    condition: cluster-svc.fluentd-elasticsearch.enabled
    tags:
      - ELK
  - name: elasticsearch-curator
    version: ^0.4.1
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    condition: cluster-svc.elasticsearch-curator.enabled
    tags:
      - ELK
  - name: nginx-ingress
    version: 0.30.0
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: cluster-svc.nginx-ingress.enabled
    tags:
      - core
  - name: cert-manager
    version: ^0.5.0
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: cluster-svc.cert-manager.enabled
    tags:
      - core
  - name: external-dns
    version: ^0.7.5
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: cluster-svc.external-dns.enabled
    tags:
      - core
  - name: metallb
    version: ^0.8.0
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: cluster-svc.metallb.enabled
    tags:
      - bare-metal
  - name: metrics-server
    version: ^2.0.2
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: cluster-svc.metrics-server.enabled
    tags:
      - core
  - name: cluster-svc-local-provisioner
    version: ^2.0.0
    repository: file://./vendored-charts/charts/local-provisioner/
    condition: cluster-svc.cluster-svc-local-provisioner.enabled
    tags:
      - bare-metal
  - name: airflow
    version: ^0.2.0-nfs-latest
    repository: https://opensource-helm.squareroute.io/
    condition: cluster-svc.airflow.enabled
  - name: chartmuseum
    version: ^1.6.2
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: cluster-svc.chartmuseum.enabled
    tags:
      - cicd
  - name: monocular
    version: ^1.2.5
    repository: https://helm.github.io/monocular
    condition: cluster-svc.monocular.enabled
    tags:
      - cicd
  - name: docker-registry
    version: ^1.6.1
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: cluster-svc.docker-registry.enabled
    tags:
      - cicd