dependencies:
  - name: grafana
    version: ^1.14.8
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: grafana.enabled
  - name: prometheus
    version: ^7.1.3
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: prometheus.enabled
  - name: elasticsearch
    version: ^1.8.1
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    condition: elasticsearch.enabled
  - name: kibana
    version: ^0.14.6
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: kibana.enabled
  - name: fluentd-elasticsearch
    version: ^0.7.2
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    condition: fluentd-elasticsearch.enabled
  - name: elasticsearch-curator
    version: ^0.4.1
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    condition: elasticsearch-curator.enabled
  - name: nginx-ingress
    version: ^0.28.2
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: nginx-ingress.enabled
  - name: cert-manager
    version: ^0.5.0
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: cert-manager.enabled
  - name: external-dns
    version: ^0.7.5
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: external-dns.enabled
  - name: metallb
    version: ^0.8.0
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: metallb.enabled
  - name: metrics-server
    version: ^2.0.2
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: metrics-server.enabled
  - name: cluster-svc-local-provisioner
    version: ^2.0.0
    repository: file://./vendored-charts/charts/local-provisioner/
    condition: cluster-svc-local-provisioner.enabled
  - name: cluster-svc-local-provisioner
    version: ^2.0.0
    repository: file://./vendored-charts/charts/local-provisioner/
    condition: cluster-svc-local-provisioner.enabled
  - name: airflow
    version: ^0.2.0-nfs-latest
    repository: https://opensource-helm.squareroute.io/
    condition: cluster-svc-airflow.enabled
  - name: chartmuseum
    version: ^1.6.2
    repository: http://kubernetes-charts.storage.googleapis.com/
    condition: chartmuseum.enabled