ssl:
  kibana:
    enabled: false
    url: kibana-dev.squareroute.io

prometheus-operator:
  enabled: false

kube-prometheus:
  deployKubeScheduler: False
  deployKubeControllerManager: False
  enabled: false

elasticsearch:
  enabled: false
  appVersion: "6.3.1"
  image:
    tag: "6.3.1"

kibana:
  enabled: false
  env:
    ELASTICSEARCH_URL: http://cluster-svc-elasticsearch-client:9200

fluentd-elasticsearch:
  enabled: false
  elasticsearch:
    host: cluster-svc-elasticsearch-client

nginx-ingress:
  enabled: true
  controller:
    service:
      externalTrafficPolicy: Local

cert-manager:
  enabled: true
  ingressShim:
    defaultIssuerName: letsencrypt-prod
    defaultIssuerKind: ClusterIssuer

elasticsearch-curator:
  enabled: false
  config:
    elasticsearch:
      hosts: 
        - cluster-svc-elasticsearch-client