{{- if .Values.ssl.kibana.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-oauth2-proxy
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: {{ .Values.ssl.kibana.url }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-oauth2-proxy
          servicePort: 80
        path: /oauth2
  tls:
  - hosts:
    - {{ .Values.ssl.kibana.url }}
    secretName: kibana-tls
{{- end -}}
